import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import utc from "dayjs/plugin/utc";
import dayjs from "dayjs";
import { css, cx } from "@styled-system/css";
import { Navbar } from "@/components/navbar";

dayjs.extend(utc);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body
        className={cx(
          css({
            bg: "black",
          }),
          inter.className
        )}
      >
        <Navbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
